'use strict';
const imgPath='icons/';
const moneyPath='money/';
const denominations=[5000,2000,1000,500,200,100,50,20,10,5,2,1];
const splitMap={5000:[2000,2000,1000],2000:[1000,1000],1000:[500,500],500:[200,200,100],200:[100,100],100:[50,50],50:[20,20,10],20:[10,10],10:[5,5],5:[2,2,1],2:[1,1]};
let settings={speech:true,difficulty:'normal',highContrast:false,priceMode:'original'};
let state={screen:'shop',activeCat:null,cart:[],paid:[],change:[],customer:1,sales:[],practice:false,practiceTask:null};
const app=document.getElementById('app');
const euro=new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'});
const fmt=c=>euro.format(c/100);
const fmtSpeak=c=>fmt(c).replace('€','Euro').replace(',00','');
const moneyLabel=c=>c>=100?`${c/100} Euro`:`${c} Cent`;
const moneyFile=c=>c>=100?`${c/100}-euro.png`:`${c}-cent.png`;
function speak(text){if(!settings.speech)return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='de-DE';u.rate=.88;speechSynthesis.speak(u)}catch(e){}}
function total(){return state.cart.reduce((s,i)=>s+i.price,0)}
function paidTotal(){return state.paid.reduce((s,v)=>s+v,0)}
function groups(){const m=new Map();state.cart.forEach(i=>{const g=m.get(i.name)||{...i,count:0,total:0};g.count++;g.total+=i.price;m.set(i.name,g)});return [...m.values()]}
function closeDialog(id){document.getElementById(id).close()} window.closeDialog=closeDialog;
function setScreen(s){state.screen=s;render();}
function init(){state.activeCat=Object.keys(PRODUCT_DATA)[0];loadSettings();bindTopButtons();render();if('serviceWorker'in navigator && location.protocol!=='file:'){navigator.serviceWorker.register('service-worker.js').catch(()=>{})}}
function bindTopButtons(){document.getElementById('helpBtn').onclick=()=>document.getElementById('helpDialog').showModal();document.getElementById('infoBtn').onclick=()=>document.getElementById('infoDialog').showModal();document.getElementById('reportBtn').onclick=openReport;document.getElementById('teacherBtn').onclick=openTeacher;document.getElementById('practiceBtn').onclick=()=>{ if(state.practice) normalMode(); else startPractice(); };document.getElementById('downloadCsvBtn').onclick=downloadCsv;document.getElementById('downloadPdfBtn').onclick=downloadPdf;}
function loadSettings(){try{const raw=localStorage.getItem('lernkasse-settings');if(raw)settings={...settings,...JSON.parse(raw)}}catch(e){}applySettingsClass()}
function saveSettings(){localStorage.setItem('lernkasse-settings',JSON.stringify(settings));applySettingsClass()}
function applySettingsClass(){document.body.classList.toggle('contrastMode',!!settings.highContrast);document.body.classList.remove('moneyStandard','moneyGross','moneyXxl','largeMode');document.body.classList.add('moneyXxl')}
function render(){document.getElementById('customerBadge').textContent=state.practice?'Übungsmodus':`Kunde ${state.customer}`;const practiceBtn=document.getElementById('practiceBtn');if(practiceBtn)practiceBtn.textContent=state.practice?'Normalmodus':'Üben'; if(state.screen==='shop') renderShop(); if(state.screen==='pay') renderPay(); if(state.screen==='change') renderChange(); if(state.screen==='done') renderDone();}
function renderShop(){const cats=Object.keys(PRODUCT_DATA);const cat=PRODUCT_DATA[state.activeCat];app.innerHTML=`<section class="screen"><div class="shopGrid"><aside class="panel catPanel"><h2>Kategorien</h2><div class="catList">${cats.map(c=>`<button class="catBtn ${catClass(c)} ${c===state.activeCat?'active':''}" data-cat="${esc(c)}">${catEmoji(c)} ${c}</button>`).join('')}</div></aside><section class="panel productPanel"><div class="productHeader"><div><h1>${catEmoji(state.activeCat)} ${state.activeCat}</h1>${state.practice?'<p class="practiceHint">Übung: Produkte liegen bereit. Kassiere diesen Einkauf.</p>':''}</div><button class="ghost dark clearCartIcon" id="clearCartBtn" title="Einkauf löschen" aria-label="Einkauf löschen">🗑️</button></div><div class="productGrid">${cat.items.map(([name,file])=>productCard(name,file)).join('')}</div></section><aside class="panel cartPanel"><h2>Warenkorb</h2><div class="cartItems">${renderCartRows()}</div><div class="totalBox"><span>Summe</span><strong>${fmt(total())}</strong></div><div class="checkoutFooter"><button class="primary" id="checkoutBtn" ${state.cart.length?'':'disabled'}>💶 Zur Kasse</button></div></aside></div></section>`;
app.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.activeCat=b.dataset.cat;render()});app.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>addProduct(b.dataset.product,b.dataset.file));app.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>removeOne(b.dataset.minus));app.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>addProduct(b.dataset.plus,b.dataset.file));document.getElementById('checkoutBtn').onclick=()=>{if(!state.cart.length)return;state.paid=[];setScreen('pay')};document.getElementById('clearCartBtn').onclick=()=>{state.cart=[];state.practice=false;state.practiceTask=null;render()};}
function productCard(name,file){return `<button class="productCard" data-product="${esc(name)}" data-file="${file}" aria-label="${esc(name)}, ${fmt(priceOf(name))}"><img src="${imgPath}${file}.png" alt="" onerror="this.style.display='none'"><span class="productName">${name}</span><span class="price">${fmt(priceOf(name))}</span></button>`}
function renderCartRows(){if(!state.cart.length)return '<p class="hint">Noch keine Produkte im Warenkorb.</p>';return groups().map(g=>`<div class="cartRow"><div><div class="cartName">${g.count}× ${g.name}</div><div class="cartMeta">${fmt(g.price)} einzeln · ${fmt(g.total)}</div></div><div class="qty"><button class="minus" data-minus="${esc(g.name)}">−</button><strong>${g.count}</strong><button data-plus="${esc(g.name)}" data-file="${g.file||''}">+</button></div></div>`).join('')}
function addProduct(name,file){state.cart.push({name,file,price:priceOf(name)});render();}
function removeOne(name){const i=state.cart.findIndex(x=>x.name===name);if(i>=0)state.cart.splice(i,1);render();}
function priceOf(name){
  const cents=Math.round((PRODUCT_PRICES[name]||1.99)*100);
  const mode=settings.priceMode||'original';
  if(mode==='full') return Math.max(100, Math.round(cents/100)*100);
  if(mode==='half') return Math.max(50, Math.round(cents/50)*50);
  if(mode==='ten') return Math.max(10, Math.round(cents/10)*10);
  return cents;
}
function renderPay(){const due=total(), paid=paidTotal();app.innerHTML=`<section class="payScreen"><div class="paySummary"><div class="bigAmount"><span>Zu bezahlen</span><strong>${fmt(due)}</strong><button class="listenMini" id="listenDueBtn" aria-label="Kaufbetrag anhören">🔊</button></div><div class="bigAmount"><span>Sie haben gegeben</span><strong>${fmt(paid)}</strong><button class="listenMini" id="listenPaidBtn" aria-label="Gegebenen Betrag anhören">🔊</button></div></div><div class="moneyArea"><div class="moneyGroup"><h2>Scheine</h2><div class="moneyGrid">${[500,1000,2000,5000].map(moneyButton).join('')}</div></div><div class="moneyGroup"><h2>Münzen</h2><div class="moneyGrid coinGrid">${[200,100,50,20,10,5,2,1].map(moneyButton).join('')}</div></div></div><div class="payFooter"><div class="paidChips" aria-label="Ausgewähltes Geld">${state.paid.length?state.paid.map((v,i)=>`<button class="chip paidChip" data-remove-paid="${i}" title="${moneyLabel(v)} entfernen" aria-label="${moneyLabel(v)} entfernen"><img src="${moneyPath}${moneyFile(v)}" alt="${moneyLabel(v)}" onerror="this.style.display='none'"></button>`).join(''):'<span class="hint payHint">Tippe auf Scheine und Münzen.</span>'}</div><div class="actions payActions"><button class="danger iconAction" id="backShopBtn" aria-label="Zurück zum Einkauf"><span class="icon">↩</span><span class="smallLabel">Zurück</span></button><button class="primary iconAction wideAction" id="showChangeBtn" aria-label="Wechselgeld zeigen" ${paid>=due?'':'disabled'}><span class="icon">💶</span><span class="smallLabel">Wechselgeld</span></button></div></div></section>`;
app.querySelectorAll('[data-money]').forEach(b=>b.onclick=()=>{const v=Number(b.dataset.money);state.paid.push(v);render()});app.querySelectorAll('[data-remove-paid]').forEach(b=>b.onclick=()=>{state.paid.splice(Number(b.dataset.removePaid),1);render()});document.getElementById('listenDueBtn').onclick=()=>speak(`Bitte bezahlen Sie ${fmtSpeak(total())}.`);document.getElementById('listenPaidBtn').onclick=()=>speak(`Sie haben ${fmtSpeak(paidTotal())} gegeben.`);document.getElementById('backShopBtn').onclick=()=>setScreen('shop');document.getElementById('showChangeBtn').onclick=()=>{state.change=makeChange(paidTotal()-total());setScreen('change')};}
function moneyButton(v){return `<button class="moneyBtn ${v>=500?'noteMoney':'coinMoney'}" data-money="${v}" aria-label="${moneyLabel(v)}"><img src="${moneyPath}${moneyFile(v)}" alt="${moneyLabel(v)}" onerror="this.style.display='none'"></button>`}
function makeChange(amount){let rest=amount,out=[];for(const d of denominations){while(rest>=d){out.push(d);rest-=d}}return out}
function renderChange(){const change=paidTotal()-total();app.innerHTML=`<section class="changeScreen"><div class="changeMain"><h1>Wechselgeld</h1><div class="changeTotal">${fmt(change)}</div><button class="listenMini changeListen" id="repeatChangeBtn" aria-label="Wechselgeld anhören">🔊</button><p class="hint">Tippe ein Geldstück an, um es kleiner zu wechseln.</p><div class="changeList">${state.change.length?state.change.map((v,i)=>`<button class="changeItem ${v>=500?'noteChange':'coinChange'}" data-split="${i}" aria-label="${moneyLabel(v)} zerlegen"><img src="${moneyPath}${moneyFile(v)}" alt="" onerror="this.style.display='none'"><span>${fmt(v)}</span></button>`).join(''):'<p class="hint">Kein Wechselgeld.</p>'}</div></div><div class="actions changeActions"><button class="danger iconAction" id="backPayBtn" aria-label="Zurück zum Bezahlen"><span class="icon">↩</span><span class="smallLabel">Zurück</span></button><button class="primary iconAction" id="finishBtn" aria-label="Kunde fertig"><span class="icon">✅</span><span class="smallLabel">Fertig</span></button></div></section>`;
app.querySelectorAll('[data-split]').forEach(b=>b.onclick=()=>splitChange(Number(b.dataset.split)));document.getElementById('repeatChangeBtn').onclick=()=>speak(`Ihr Wechselgeld beträgt ${fmtSpeak(change)}.`);document.getElementById('backPayBtn').onclick=()=>setScreen('pay');document.getElementById('finishBtn').onclick=finishSale;}
function splitChange(i){const v=state.change[i];if(!splitMap[v])return;speak(`${moneyLabel(v)} wird kleiner gewechselt.`);state.change.splice(i,1,...splitMap[v]);render();}
function finishSale(){state.sales.push({customer:state.practice?'Übung':state.customer,total:total(),paid:paidTotal(),change:paidTotal()-total(),items:groups().map(g=>`${g.count}× ${g.name}`).join(', '),time:new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})});setScreen('done');}
function renderDone(){app.innerHTML=`<section class="doneScreen"><div class="doneCard"><div class="stars">⭐⭐⭐</div><h1>${state.practice?'Übung geschafft!':'Gut gemacht!'}</h1><div class="actions"><button class="primary goodbyeBtn" id="nextCustomerBtn">👋 Auf Wiedersehen und einen schönen Tag</button></div></div></section>`;document.getElementById('nextCustomerBtn').onclick=()=>{speak('Auf Wiedersehen und einen schönen Tag.');state.practice=false;state.practiceTask=null;state.customer++;state.cart=[];state.paid=[];state.change=[];setScreen('shop')}}
function openReport(){const sum=state.sales.reduce((s,x)=>s+x.total,0);document.getElementById('reportContent').innerHTML=state.sales.length?`<p><strong>${state.sales.length}</strong> Verkäufe · Tageswert <strong>${fmt(sum)}</strong></p><table class="reportTable"><thead><tr><th>Kunde</th><th>Zeit</th><th>Summe</th><th>Gegeben</th><th>Wechselgeld</th></tr></thead><tbody>${state.sales.map(s=>`<tr><td>${s.customer}</td><td>${s.time}</td><td>${fmt(s.total)}</td><td>${fmt(s.paid)}</td><td>${fmt(s.change)}</td></tr>`).join('')}</tbody></table>`:'<p>Noch keine Verkäufe.</p>';document.getElementById('reportDialog').showModal();}
function downloadCsv(){const rows=[['Kunde','Zeit','Artikel','Summe','Gegeben','Wechselgeld'],...state.sales.map(s=>[s.customer,s.time,s.items,fmt(s.total),fmt(s.paid),fmt(s.change)])];const csv=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='lernkasse-protokoll.csv';a.click();}
function downloadPdf(){const sum=state.sales.reduce((s,x)=>s+x.total,0);const rows=state.sales.map(s=>`<tr><td>${esc(s.customer)}</td><td>${esc(s.time)}</td><td>${esc(s.items)}</td><td>${fmt(s.total)}</td><td>${fmt(s.paid)}</td><td>${fmt(s.change)}</td></tr>`).join('');const html=`<!doctype html><html lang="de"><head><meta charset="utf-8"><title>Lernkasse Protokoll</title><style>body{font-family:Arial,sans-serif;margin:24px;color:#111}h1{margin:0 0 8px}p{font-size:14px}table{width:100%;border-collapse:collapse;margin-top:16px;font-size:12px}th,td{border:1px solid #999;padding:7px;text-align:left;vertical-align:top}th{background:#eee}.toolbar{margin-bottom:16px}.btn{border:0;border-radius:10px;background:#2e7d32;color:white;padding:12px 16px;font-weight:bold;cursor:pointer}@media print{.toolbar{display:none}body{margin:14mm}}</style></head><body><div class="toolbar"><button class="btn" onclick="window.print()">PDF speichern / drucken</button></div><h1>Verkaufsprotokoll Lernkasse</h1><p>Datum: ${new Date().toLocaleDateString('de-DE')} · Verkäufe: ${state.sales.length} · Tageswert: ${fmt(sum)}</p>${state.sales.length?`<table><thead><tr><th>Kunde</th><th>Zeit</th><th>Artikel</th><th>Summe</th><th>Gegeben</th><th>Wechselgeld</th></tr></thead><tbody>${rows}</tbody></table>`:'<p>Noch keine Verkäufe.</p>'}<script>setTimeout(()=>window.print(),300)<\/script></body></html>`;const w=window.open('','_blank');if(!w){alert('Bitte Pop-ups erlauben, um das Protokoll als PDF zu speichern.');return;}w.document.write(html);w.document.close();}
function openTeacher(){document.getElementById('teacherContent').innerHTML=`<div class="teacherGrid"><label><input type="checkbox" id="setSpeech" ${settings.speech?'checked':''}> Sprache über Vorlese-Tasten</label><label><input type="checkbox" id="setContrast" ${settings.highContrast?'checked':''}> Hoher Kontrast</label><label>Schwierigkeit <select id="setDifficulty"><option value="leicht" ${settings.difficulty==='leicht'?'selected':''}>leicht</option><option value="normal" ${settings.difficulty==='normal'?'selected':''}>normal</option><option value="schwer" ${settings.difficulty==='schwer'?'selected':''}>schwer</option></select></label><label>Preise <select id="setPriceMode"><option value="original" ${settings.priceMode==='original'?'selected':''}>Originalpreise</option><option value="full" ${settings.priceMode==='full'?'selected':''}>nur volle Euro</option><option value="half" ${settings.priceMode==='half'?'selected':''}>50-Cent-Schritte</option><option value="ten" ${settings.priceMode==='ten'?'selected':''}>10-Cent-Schritte</option></select></label></div><p class="hint">Geld wird immer groß angezeigt. Die Preisstufe wirkt sofort auf Produkte und Übungsmodus.</p><div class="actions"><button class="secondary" id="teacherPracticeBtn">Übung starten</button><button class="danger" id="clearDayBtn">Protokoll löschen</button></div>`;document.getElementById('setSpeech').onchange=e=>{settings.speech=e.target.checked;saveSettings()};document.getElementById('setContrast').onchange=e=>{settings.highContrast=e.target.checked;saveSettings()};document.getElementById('setDifficulty').onchange=e=>{settings.difficulty=e.target.value;saveSettings()};document.getElementById('setPriceMode').onchange=e=>{settings.priceMode=e.target.value;state.cart=state.cart.map(i=>({...i,price:priceOf(i.name)}));saveSettings();render()};document.getElementById('teacherPracticeBtn').onclick=()=>{document.getElementById('teacherDialog').close();startPractice()};document.getElementById('clearDayBtn').onclick=()=>{if(confirm('Protokoll wirklich löschen?')){state.sales=[];document.getElementById('teacherDialog').close();}};document.getElementById('teacherDialog').showModal();}
function normalMode(){state.practice=false;state.practiceTask=null;state.cart=[];state.paid=[];state.change=[];setScreen('shop');speak('Normalmodus.');}
function startPractice(){state.practice=true;state.cart=[];state.paid=[];state.change=[];const all=[];Object.values(PRODUCT_DATA).forEach(cat=>cat.items.forEach(([name,file])=>all.push({name,file})));const count=settings.difficulty==='leicht'?2:settings.difficulty==='schwer'?5:3;for(let i=0;i<count;i++){const p=all[Math.floor(Math.random()*all.length)];state.cart.push({name:p.name,file:p.file,price:priceOf(p.name)});if(settings.difficulty!=='leicht' && Math.random()>.55)state.cart.push({name:p.name,file:p.file,price:priceOf(p.name)});}state.activeCat=Object.keys(PRODUCT_DATA)[0];setScreen('shop');speak('Kassiere den Einkauf.');}
function catEmoji(c){return {'Milchprodukte':'🥛','Gemüse':'🥦','Obst':'🍎','Fleisch':'🥩','Wurst':'🌭','Fisch & Ei':'🐟','Konserven':'🥫','Getreide & Hülsenfrüchte':'🌾','Gewürze & Öl':'🧂','Süßes':'🍬','Sonstiges':'🛒'}[c]||'📦'}
function catClass(c){return {'Milchprodukte':'cat-milch','Gemüse':'cat-gemuese','Obst':'cat-obst','Fleisch':'cat-fleisch','Wurst':'cat-wurst','Fisch & Ei':'cat-fisch','Konserven':'cat-konserven','Getreide & Hülsenfrüchte':'cat-getreide','Gewürze & Öl':'cat-gewuerze','Süßes':'cat-suess','Sonstiges':'cat-sonstiges'}[c]||'cat-sonstiges'}
function esc(s){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
window.addEventListener('DOMContentLoaded',init);
