window.PRODUCT_DATA = {
"Milchprodukte":{class:"milch",items:[["Butter","butter"],["Crème Fine","creme_fine"],["Crème Fraîche","creme_fraiche"],["Emmentaler","emmentaler"],["Feta","feta"],["Frischkäse","frischkaese"],["Joghurt","joghurt"],["Käse","kaese"],["Mascarpone","mascarpone"],["Milch","milch"],["Mozzarella","mozzarella"],["Parmesan","parmesan"],["Quark","quark"],["Saure Sahne","saure_sahne"],["Schlagsahne","schlagsahne"],["Schmand","schmand"]]},
"Gemüse":{class:"gemuese",items:[["Blumenkohl","blumenkohl"],["Brokkoli","brokkoli"],["Champignons","champignons"],["Erbsen","erbsen"],["Gurke","gurke"],["Karotten","karotte"],["Kartoffeln","kartoffeln"],["Knoblauch","knoblauch"],["Kürbis","kuerbis"],["Lauch","lauch"],["Paprika","paprika"],["Salat","salat"],["Spinat","spinat"],["Tomaten","tomate"],["Zucchini","zucchini"],["Zwiebeln","zwiebel"]]},
"Obst":{class:"obst",items:[["Apfel","apfel"],["Banane","banane"],["Birne","birne"],["Erdbeeren","erdbeeren"],["Kiwi","kiwi"],["Mandarinen","mandarinen"],["Nektarine","nektarine"],["Trauben","trauben"],["Zitrone","zitrone"]]},
"Fleisch":{class:"fleisch",items:[["Hackfleisch","hackfleisch"],["Speckwürfel","speckwuerfel"]]},
"Wurst":{class:"wurst",items:[["Grillwürstchen","grillwuerstchen"],["Kochschinken","kochschinken"],["Leberwurst","leberwurst"],["Mortadella","mortadella"],["Salami","salami"],["Teewurst","teewurst"],["Wiener","wiener"]]},
"Fisch & Ei":{class:"fisch",items:[["Eier","eier"],["Fischstäbchen","fischstaebchen"],["Thunfisch","thunfisch"],["TK Lachs","tk_lachs"]]},
"Konserven":{class:"konserven",items:[["Apfelmus","apfelmus"],["Ananas","ananas"],["Dosenmais","dosenmais"],["Dosenpfirsiche","dosenpfirsiche"],["Dosentomaten","dosentomaten"],["Getrocknete Tomaten","getrocknete_tomaten"],["Kokosmilch","kokosmilch"],["Passierte Tomaten","passierte_tomaten"],["Saure Gurken","saure_gurken"],["Schattenmorellen","schattenmorellen"]]},
"Getreide & Hülsenfrüchte":{class:"getreide",items:[["Blätterteig","blaetterteig"],["Brötchen","broetchen"],["Brot","brot"],["Haferflocken","haferflocken"],["Mehl","mehl"],["Müsli","muesli"],["Nudeln","nudeln"],["Pizzateig","pizzateig"],["Reis","reis"],["Rote Linsen","rote_linsen"],["Tortellini","tortellini"],["Yum Yum","yum_yum"]]},
"Gewürze & Öl":{class:"gewuerze",items:[["Balsamico","balsamico"],["Basilikum","basilikum"],["Curry","curry"],["Essig","essig"],["Gemüsebrühe","gemuesebruehe"],["Italienische Kräuter","italienische_kraeuter"],["Ketchup","ketchup"],["Majoran","majoran"],["Mayonnaise","mayonnaise"],["Muskatnuss","muskatnuss"],["Olivenöl","olivenoel"],["Oregano","oregano"],["Paprikapulver","paprikapulver"],["Petersilie","petersilie"],["Pfeffer","pfeffer"],["Rapsöl","rapsoel"],["Salz","salz"],["Schnittlauch","schnittlauch"],["Senf","senf"],["Sonnenblumenöl","sonnenblumenoel"],["Zimt","zimt"]]},
"Süßes":{class:"suess",items:[["Cookies","cookies"],["Honig","honig"],["Lebensmittelfarbe","lebensmittelfarbe"],["Nüsse","nuesse"],["Nutella","nutella"],["Oreo","oreo"],["Puderzucker","puderzucker"],["Schokoküsse","schokokuesse"],["Schokopudding","schokopudding"],["Toffifee","toffifee"],["Vanillepudding","vanillepudding"],["Zuckerstreusel","zuckerstreusel"]]},
"Sonstiges":{class:"sonstiges",items:[["Backpulver","backpulver"],["Sahnesteif","sahnesteif"],["Tee","tee"],["Trockenhefe","trockenhefe"],["Vanillezucker","vanillezucker"],["Zucker","zucker"]]}
};
window.PRODUCT_PRICES = {
  "Butter": 2.49,
  "Crème Fine": 1.49,
  "Crème Fraîche": 1.39,
  "Emmentaler": 2.29,
  "Feta": 1.79,
  "Frischkäse": 1.29,
  "Joghurt": 0.69,
  "Käse": 2.49,
  "Mascarpone": 2.19,
  "Milch": 1.19,
  "Mozzarella": 1.09,
  "Parmesan": 2.99,
  "Quark": 1.09,
  "Saure Sahne": 0.89,
  "Schlagsahne": 1.19,
  "Schmand": 0.99,
  "Blumenkohl": 2.49,
  "Brokkoli": 1.79,
  "Champignons": 1.99,
  "Erbsen": 1.29,
  "Gurke": 0.99,
  "Karotten": 1.49,
  "Kartoffeln": 2.99,
  "Knoblauch": 0.49,
  "Kürbis": 2.79,
  "Lauch": 1.29,
  "Paprika": 1.49,
  "Salat": 1.29,
  "Spinat": 1.79,
  "Tomaten": 2.49,
  "Zucchini": 0.89,
  "Zwiebeln": 1.29,
  "Apfel": 0.59,
  "Banane": 0.39,
  "Birne": 0.69,
  "Erdbeeren": 3.49,
  "Kiwi": 0.59,
  "Mandarinen": 2.49,
  "Nektarine": 0.79,
  "Trauben": 2.99,
  "Zitrone": 0.49,
  "Hackfleisch": 4.49,
  "Speckwürfel": 2.29,
  "Grillwürstchen": 3.49,
  "Kochschinken": 2.29,
  "Leberwurst": 1.79,
  "Mortadella": 1.99,
  "Salami": 2.49,
  "Teewurst": 1.89,
  "Wiener": 2.99,
  "Eier": 2.79,
  "Fischstäbchen": 2.49,
  "Thunfisch": 1.79,
  "TK Lachs": 5.99,
  "Apfelmus": 1.39,
  "Ananas": 1.49,
  "Dosenmais": 0.99,
  "Dosenpfirsiche": 1.79,
  "Dosentomaten": 0.89,
  "Getrocknete Tomaten": 2.49,
  "Kokosmilch": 1.69,
  "Passierte Tomaten": 1.09,
  "Saure Gurken": 1.69,
  "Schattenmorellen": 2.19,
  "Blätterteig": 1.49,
  "Brötchen": 0.39,
  "Brot": 2.79,
  "Haferflocken": 0.99,
  "Mehl": 0.89,
  "Müsli": 2.49,
  "Nudeln": 1.29,
  "Pizzateig": 1.79,
  "Reis": 1.99,
  "Rote Linsen": 1.79,
  "Tortellini": 2.49,
  "Yum Yum": 0.79,
  "Balsamico": 2.49,
  "Basilikum": 1.29,
  "Curry": 1.49,
  "Essig": 0.99,
  "Gemüsebrühe": 1.49,
  "Italienische Kräuter": 1.29,
  "Ketchup": 1.99,
  "Majoran": 1.09,
  "Mayonnaise": 1.79,
  "Muskatnuss": 1.49,
  "Olivenöl": 5.49,
  "Oregano": 1.09,
  "Paprikapulver": 1.29,
  "Petersilie": 1.19,
  "Pfeffer": 1.49,
  "Rapsöl": 2.49,
  "Salz": 0.49,
  "Schnittlauch": 1.19,
  "Senf": 0.99,
  "Sonnenblumenöl": 2.29,
  "Zimt": 1.29,
  "Cookies": 1.99,
  "Honig": 3.49,
  "Lebensmittelfarbe": 1.99,
  "Nüsse": 2.99,
  "Nutella": 3.49,
  "Oreo": 1.99,
  "Puderzucker": 0.89,
  "Schokoküsse": 1.79,
  "Schokopudding": 0.79,
  "Toffifee": 2.29,
  "Vanillepudding": 0.79,
  "Zuckerstreusel": 1.49,
  "Backpulver": 0.49,
  "Sahnesteif": 0.59,
  "Tee": 1.79,
  "Trockenhefe": 0.39,
  "Vanillezucker": 0.49,
  "Zucker": 1.09
};
